### ISSUE TITLE
Unable to locate package battery-monitor-y

### ISSUE THREAD

**Issue by Mehedi61** [maateen/battery-monitor#12]
I've tried to install battery
![bamscreenshot from 2016-07-29 23 37 32](https://cloud.githubusercontent.com/assets/17181344/17257921/3d2a301c-55e6-11e6-9420-57985eea69e0.png)
 monitor from repository,though i already installed it from .deb file. I use Ubuntu 14.04 LTS. When i try "sudo apt-get install battery-monitor-y" command , it shows this problem.

**Comment by maateen** [comment]
Do you still feel the issue? Follow these steps:

```
sudo add-apt-repository ppa:maateen/battery-monitor -y
sudo apt-get update
sudo apt-get install battery-monitor -y
```

**Comment by Mehedi61** [comment]
Fine. These steps worked nicely.
