### ISSUE TITLE
Not working on Gnome desktop

### ISSUE THREAD

**Issue by meetdilip** [maateen/battery-monitor#15]
I have Gnome desktop along with Unity. But while using Unity, I got no warning for low battery. Thought of reporting.
##

**Comment by maateen** [comment]
So, is isn't working on Unity, not GNOME?

**Comment by meetdilip** [comment]
Tested only on Unity.

**Comment by maateen** [comment]
>I got no warning for low battery.

Are other events working fine?

**Comment by meetdilip** [comment]
Everything working fine on Unity. I didn't check extensively on Gnome 3. I was on it and I got no notifications.

**Comment by maateen** [comment]
Okay. As soon as we can't ensure the issue, we can't label it as bug.

**Comment by meetdilip** [comment]
I can confirm that I got not warning on low battery with Gnome on 16.04

**Comment by maateen** [comment]
@meetdilip We have released a new version of **Battery Monitor**. Please try that and let us whether the problem has been fixed or not. Here is the details: http://battery-monitor.maateen.me/
