### ISSUE TITLE
[Bug] Notification not staying on top

### ISSUE THREAD

**Issue by meetdilip** [maateen/battery-monitor#16]
Unity 7 in 16.04. I was watching a video in VLC in full screen mode. I got no 30 % notification. There was a 10 % low battery warning. But, I guess, that is from the system. Please check.
##

**Comment by maateen** [comment]
@meetdilip We have released a new version of **Battery Monitor**. Please try that and let us whether the problem has been fixed or not. Here is the details: http://battery-monitor.maateen.me/
