### ISSUE TITLE
After user logout or PC restart it does not run automatically in background.

### ISSUE THREAD

**Issue by qhroman** [maateen/battery-monitor#17]
I have Ubuntu 16.04 installed on Lenovo Yoga Pro 2 laptop. Installation has been done in terminal from PPA according this link: http://lab.maateen.me/battery-monitor/
I can start it manually through Alt-F2 and it runs no problem but when I logout or restart laptop I have to start it again manually. How to add the program into laptop boot?
Thank you,
Roman.
##

**Comment by maateen** [comment]
It's a known bug, many users have faced. But you can do a temporary fix from here: #5

**Comment by maateen** [comment]
@qhroman We have released a new version of **Battery Monitor**. Please try that and let us whether the problem has been fixed or not. Here is the details: http://battery-monitor.maateen.me/
