### ISSUE TITLE
Not Working on Ubuntu 16.04

### ISSUE THREAD

**Issue by asadlive84** [maateen/battery-monitor#18]
I have Ubuntu 16.04 installed on laptop. I installed battery monitor apps from terminal. I see this app on my dash board but it cant work. I was trying to many times for using this app. But It cant work. 
My OS: Ubuntu 16.04.1 (64 bit/Dual Boot)

**Comment by maateen** [comment]
It's a known bug, many users have faced. We will fix it in upcoming version. But you can do a temporary fix from here: #5

**Comment by maateen** [comment]
@asadlive84 We have released a new version of **Battery Monitor**. Please try that and let us whether the problem has been fixed or not. Here is the details: http://battery-monitor.maateen.me/
