### ISSUE TITLE
Notification issue in Ubuntu Gnome 16.04

### ISSUE THREAD

**Issue by maateen** [maateen/battery-monitor#19]
Every time a notification is triggered in Gnome3, the notification goes within a blink of eyes.

**Comment by abougouffa** [comment]
I think this bug have been fixed in https://github.com/maateen/battery-monitor/commit/86c218aa9307c4d70722c3343264d86f2a7ff853

**Comment by maateen** [comment]
#86c218a has fixed the issue as @abougouffa said.
