### ISSUE TITLE
The app does not work in Xubuntu 16.04.1 (64 bit)

### ISSUE THREAD

**Issue by Pavel-Sayekat** [maateen/battery-monitor#2]
The app does not work in Xubuntu 16.04.1 (64 bit), http://paste.ubuntu.com/20562844/, and after installation and calling the program from CLI, no sign, http://pasteboard.co/ePmJlo4Gn.png, like to add, my battery has 1-2 minutes backup, means it has been degraded but still Xubuntu app is showing the battery.

**Comment by maateen** [comment]
Thanks for the elaboration. I need more info, please co-operate. Play the command and paste the output here:
```
acpi -b
```
It will show some result depending on battery condition.

**Comment by Pavel-Sayekat** [comment]
$ acpi -b
Battery 0: Unknown, 16%

**Comment by Pavel-Sayekat** [comment]
a better approach,
$ acpi -V
Battery 0: Unknown, 16%
Battery 0: design capacity 407 mAh, last full capacity 2599 mAh = 100%
Adapter 0: on-line
Thermal 0: ok, 71.0 degrees C
Thermal 0: trip point 0 switches to mode critical at temperature 100.0 degrees C
Cooling 0: LCD 10 of 10
Cooling 1: Processor 0 of 7

**Comment by maateen** [comment]
Thanks for the info. Let's play these:

```
wget https://raw.githubusercontent.com/maateen/battery-monitor/e51be08efbc755431743f61a53f419bd504acd18/battery-monitor.py
```
```
python3 battery-monitor.py
```

Any update? Please plug the charger or unplug. Do it random, you should get different notification.

**Comment by Pavel-Sayekat** [comment]
Ran that, but no change, plugged and unplugged the AC power but the notification is coming from Power Manager, no notification from Battery Manager. Try to look for other machines if if works, It works for your machine I see, :)

**Comment by maateen** [comment]
Hope, I will fix it soon.

**Comment by maateen** [comment]
Q. Why this issue occurs?
A. May be, PyGtk3 can't be integrated nicely with Xubuntu. [source](http://askubuntu.com/questions/802928/gtk-3-theming-problems-in-xubuntu-16-04)

Give it a try:
```
sudo apt-get install libgtk-3-dev
```
Then try the app again. 
> I don't use Xubuntu or I don't even have  a live CD. So I can't debug the app there.

**Comment by Pavel-Sayekat** [comment]
installed libgtk-3-dev and even upgraded the battery-monitor and all today but to no avail, no app notification or alt+tab showing no window, ran in terminal "battery-monitor", in normal mode and in root mode with no results. Its okay if it doesn't work and great if it works :+1:

**Comment by maateen** [comment]
Okay, let the issue be be opened. I will test something on your PC via TeamViewer one day, if you agree.

**Comment by Pavel-Sayekat** [comment]
OK, we will see.

**Comment by Pavel-Sayekat** [comment]
It works now in Xubuntu 16.04 64 bit, wow :), May be the expired battery was the issue, on a different machine whose battery is in good state works fine with your battery monitor, yea...
