### ISSUE TITLE
Battery Monitor disarrange default battery icon

### ISSUE THREAD

**Issue by PandaJim** [maateen/battery-monitor#3]
In 64-bit Ubuntu 16.04 Unity, the default battery icon on panel sometimes messed up after started battery-monitor. 

It displays the uncharging icon when I plug in power supply, and shows the charging icon when I pull out the power supply, though battery-monitor shows correct notifications.

**Comment by maateen** [comment]
I am using the same configuration. But I'm not getting this issue. Also, with the default indicator, battery-monitor has no contradiction. :open_mouth: 
Can you elaborate the issue more?

**Comment by meetdilip** [comment]
Working fine for me with the same specs.

**Comment by maateen** [comment]
@PandaJim We have released a new version of **Battery Monitor**. Please try that and let us whether the problem has been fixed or not. Here is the details: http://battery-monitor.maateen.me/
