### ISSUE TITLE
I didn’t get the remaining time for charging, discharging, etc in notification.

### ISSUE THREAD

**Issue by 2daygeek** [maateen/battery-monitor#32]
Is there any limitation for VM's. Check the screenshot for details. 

http://www.2daygeek.com/monitor-laptop-battery-linux/

**Comment by maateen** [comment]
Can you please give me the output of the following command:

```
acpi -b
```

**Comment by 2daygeek** [comment]
I got the same output.

**Comment by maateen** [comment]
Actually, I have tried to ask you the command line output after playing the following command on Terminal:

```
acpi -b
```

**Comment by 2daygeek** [comment]
Please find the output.

magi@daygeek:~$ acpi -b
Battery 0: Charging, 28%, charging at zero rate - will never fully charge.

**Comment by maateen** [comment]
Please look at the output. That's why Battery Monitor never shows the Battery percentage.
