### ISSUE TITLE
Make error in Antergos 

### ISSUE THREAD

**Issue by RezwanArefin01** [maateen/battery-monitor#35]
I am having this error after running sudo make install. 
```
make: Circular all <- install dependency dropped.
You must be root to install.
cp: cannot create regular file '/root/.config/autostart/battery-monitor.desktop': No such file or directory
```

**Comment by maateen** [comment]
Did you use `sudo make install` command? Or have you used `make install` as a superuser?

**Comment by RezwanArefin01** [comment]
I used `sudo make install`.... mentioned in issue :(

**Comment by Vistaus** [comment]
Same problem on Solus :(

```
[10:38:40] vistaus@vistaus-solus /media/MicroSD/Apps/battery-monitor (2) 
> sudo make install
make: Circular all <- install dependency dropped.
You must be root to install.
cp: cannot create regular file '/root/.config/autostart/battery-monitor.desktop': No such file or directory
make: *** [Makefile:16: install] Error 1
[10:38:45] vistaus@vistaus-solus /media/MicroSD/Apps/battery-monitor (2) 
```

**Comment by maateen** [comment]
Okay, I've got it. I'll fix this soon and make another release. Once I've done, I'll let you know.

**Comment by Vistaus** [comment]
That's great to hear! Thanks for the quick response! :smile:

**Comment by maateen** [comment]
I have pushed a new commit to **devel** branch. Please try the Beta version from here: https://github.com/maateen/battery-monitor#for-beta-testers and then let me know the update.

**Comment by Vistaus** [comment]
@maateen It still outputs that I need to be root

(> sudo make install
You must be root to install.
Installation completed!
[15:13:20] vistaus@vistaus-solus /media/MicroSD/Apps/battery-monitor (0) 
> )

but the install does complete and the GUI works, so I'll test if the rest of the app works as well and let you know. Thanks for the quick fixin'! :smile:

**Comment by maateen** [comment]
@Vistaus _You must be root to install._ is just a reminder. Nothing to worry.

**Comment by Vistaus** [comment]
@maateen It doesn't seem to install correctly still 'cause when I start battery-monitor, it just gives me a white overlay that I can't get rid of. Let me know if it's related to this issue, else I'll open up a new issue.

![Uploading Screenshot from 2017-03-16 15:17:23.png…]()

**Comment by maateen** [comment]
@Vistaus Please open a new issue. :) It's a bug.
