### ISSUE TITLE
White overlay in top right corner after starting battery-monitor

### ISSUE THREAD

**Issue by Vistaus** [maateen/battery-monitor#38]
Battery Monitor doesn't seem to install correctly 'cause when I start battery-monitor, it just gives me a white overlay in the top right corner that I can't get rid of.

![screenshot from 2017-03-16 15 17 23](https://cloud.githubusercontent.com/assets/1716229/24000582/e42f8c0c-0a5b-11e7-89ba-09d3bd6b91bb.png)

**Comment by maateen** [comment]
Battery Monitor has four dependencies. Have you installed them?

- python3
- python3-gi
- libnotify-dev
- acpi

**Comment by Vistaus** [comment]
Yes, they are all installed.

**Comment by maateen** [comment]
Still getting the issues? What's the terminal output of following command:

```
python3 /usr/share/battery-monitor/battery-monitor.py
```

Any error occurred?

**Comment by Vistaus** [comment]
Yes, it outputs this error:

```
> python3 /usr/share/battery-monitor/battery-monitor.py
Press 'ctrl+C' to exit.
/usr/share/battery-monitor/battery-monitor.py:226: Warning: gsignal.c:2641: instance '0xfad0a0' has no handler with id '6'
  del notification
[18:58:36] vistaus@vistaus-solus /media/MicroSD/Apps/battery-monitor (0) 
> 
```

**Comment by maateen** [comment]
Are you using Mate desktop?

**Comment by Vistaus** [comment]
Nope, I'm using Budgie desktop.

**Comment by maateen** [comment]
There's a same issue reported in Mate, check here please: https://bugzilla.redhat.com/show_bug.cgi?id=1005519. I think the problem is Budgie based. Rather I have labeled the issue to be fixed.
