### ISSUE TITLE
Exits on startup. 

### ISSUE THREAD

**Issue by Connorabruce** [maateen/battery-monitor#39]
Since adding the PPA and updating to the new version I have been unable to get battery monitor to run on Ubuntu 16.10. It crashes after a few seconds. This is what I get when I run it from the terminal:

`~$ battery-monitor
Press 'ctrl+C' to exit.
Traceback (most recent call last):
  File "/usr/share/battery-monitor/battery-monitor.py", line 193, in <module>
    notification.show_specific_notifications(monitor)
  File "/usr/share/battery-monitor/battery-monitor.py", line 153, in show_specific_notifications
    elif percentage == int(self.second_custom_warning):
ValueError: invalid literal for int() with base 10: ''

(process:8551): GLib-CRITICAL **: g_hash_table_destroy: assertion 'hash_table != NULL' failed
Exception ignored in: <bound method Notification.__del__ of <__main__.Notification object at 0x7f9b6fc8d828>>
Traceback (most recent call last):
  File "/usr/share/battery-monitor/battery-monitor.py", line 183, in __del__
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable
`

Thanks.

**Comment by maateen** [comment]
What have you set as **Second Custom Warning**?

**Comment by Connorabruce** [comment]
It is blank. First custom warning is 80%. Low is 18 and critical is 12. Second and third are both empty.

**Comment by Connorabruce** [comment]
Not sure whether this is of any help, but I have been playing around with the program. It seems that whatever percentage is placed in any of the custom warnings will cause it to crash when that percentage is reached and it tries to display a notification. 

As a workaround I set all the custom warnings to 101% (so they never trigger) and set the Low and Very Low warnings as normal and everything seems to work fine then. The normal Low Battery warning is displayed when the Low percentage is reached.

**Comment by maateen** [comment]
I have already fixed the issue in **Beta**. You can try it from here: https://github.com/maateen/battery-monitor#for-beta-testers
