### ISSUE TITLE
Warning @ 30 %

### ISSUE THREAD

**Issue by meetdilip** [maateen/battery-monitor#4]
Any chance we can have a warning at 30 % for low battery ?

**Comment by meetdilip** [comment]
Thanks, just noticed that there is one notification at 27 %

**Comment by maateen** [comment]
I will add a GUI soon, and anyone can get notification at any level. Currently it's only at <=10%.

**Comment by meetdilip** [comment]
Also, don't get carried away by negative comments on OMG. People like to criticise :(

**Comment by maateen** [comment]
@meetdilip Thanks. I am new to GUI development. I am trying my level best.
