### ISSUE TITLE
Error on running with no power cable / removing power cable

### ISSUE THREAD

**Issue by kiaroa** [maateen/battery-monitor#42]
Running ubuntu 17.04 zesty.

With power cable in, it starts fine, then correctly shows time to full charge.

If started with power cable out, or cable is removed after starting I get this:
```
Traceback (most recent call last):
  File "/usr/share/battery-monitor/battery-monitor.py", line 197, in <module>
    notification.show_specific_notifications(monitor)
  File "/usr/share/battery-monitor/battery-monitor.py", line 145, in show_specific_notifications
    elif percentage == int(self.first_custom_warning):
ValueError: invalid literal for int() with base 10: ''

(process:24772): GLib-GObject-WARNING **: ../../../../gobject/gsignal.c:2641: instance '0x55fb26e680a0' has no handler with id '7'

```

**Comment by kiaroa** [comment]
Pobably missing values, line 78. I've inserted these values, and error seems resolved:
        self.first_custom_warning = '25'
        self.second_custom_warning = '20'
        self.third_custom_warning = '15'

**Comment by maateen** [comment]
I'm gonna fix the bug soon. Also I'll introduce automated testing to make the project bug free in near future.

**Comment by maateen** [comment]
I can remember that once I've fixed it but somehow I haven't pushed that code to upstream.

**Comment by maateen** [comment]
@kiaroa I have pushed a new commit to **devel** branch. This should fix your issue. Though I haven't merged this with **master** branch, but you can test this from [here](https://github.com/maateen/battery-monitor/tree/devel#for-developers). Please let me know the updates.
