### ISSUE TITLE
AttributeError: module 'gi' has no attribute 'require_version'

### ISSUE THREAD

**Issue by jecogeo** [maateen/battery-monitor#45]
When I execute Battery Monitor file located in /usr/share/battery-monitor, everything goes straightforward. I usually start the application through Ubuntu Dash. However the `battery-monitor` command in the terminal returns: 
```
Traceback (most recent call last):
File "/usr/share/battery-monitor/battery-monitor.py", line 12, in <module>
gi.require_version('Notify', '0.7')
AttributeError: module 'gi' has no attribute 'require_version' 
```

I'm would like to insert the `battery-monitor` command in Startup Applications.

Any idea?

**Comment by maateen** [comment]
Please let me know about your OS and how you have installed Battery Monitor.

**Comment by jecogeo** [comment]
Oh, sure. Forgot it. I'm using Ubuntu 16.04 LTS and installed Battery Monitor via `sudo apt-get install battery-monitor`.

**Comment by maateen** [comment]
I think you're missing `python-gobject` somehow. Please install it.

**Comment by jecogeo** [comment]
python-gobject is already the newest version (3.20.0-0ubuntu1)

**Comment by maateen** [comment]
Sorry for my late reply. Can you please show me the command line output of these commands:

```
which python3
```
```
python3 -c "import gi; print(gi.__spec__)"
```
```
python3 -c "import gi; print(gi.__dict__)"
```

**Comment by jecogeo** [comment]
jeco@jeco-pc  ~  which python3
/home/jeco/anaconda3/bin/python3
 jeco@jeco-pc  ~  python3 -c "import gi; print(gi.__spec__)" 
ModuleSpec(name='gi', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7fe5ecbb93c8>, origin='/home/jeco/anaconda3/lib/python3.5/site-packages/gi/__init__.py', submodule_search_locations=['/home/jeco/anaconda3/lib/python3.5/site-packages/gi'])
 jeco@jeco-pc  ~  python3 -c "import gi; print(gi.__dict__)"
{'__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7f9392f6c3c8>, '__builtins__': {'ord': <built-in function ord>, 'BrokenPipeError': <class 'BrokenPipeError'>, 'PermissionError': <class 'PermissionError'>, 'UnicodeError': <class 'UnicodeError'>, 'EOFError': <class 'EOFError'>, 'print': <built-in function print>, 'IndexError': <class 'IndexError'>, 'OSError': <class 'OSError'>, 'dir': <built-in function dir>, 'NotImplementedError': <class 'NotImplementedError'>, 'delattr': <built-in function delattr>, 'ResourceWarning': <class 'ResourceWarning'>, 'classmethod': <class 'classmethod'>, 'staticmethod': <class 'staticmethod'>, 'hex': <built-in function hex>, 'InterruptedError': <class 'InterruptedError'>, 'list': <class 'list'>, '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>), 'SystemExit': <class 'SystemExit'>, 'NameError': <class 'NameError'>, '__debug__': True, 'SyntaxError': <class 'SyntaxError'>, 'max': <built-in function max>, 'BaseException': <class 'BaseException'>, 'getattr': <built-in function getattr>, 'GeneratorExit': <class 'GeneratorExit'>, 'super': <class 'super'>, 'iter': <built-in function iter>, 'UnicodeDecodeError': <class 'UnicodeDecodeError'>, 'format': <built-in function format>, 'None': None, 'StopAsyncIteration': <class 'StopAsyncIteration'>, 'exec': <built-in function exec>, 'locals': <built-in function locals>, 'min': <built-in function min>, 'UserWarning': <class 'UserWarning'>, 'any': <built-in function any>, 'OverflowError': <class 'OverflowError'>, 'EnvironmentError': <class 'OSError'>, 'NotADirectoryError': <class 'NotADirectoryError'>, 'type': <class 'type'>, 'RuntimeError': <class 'RuntimeError'>, 'Ellipsis': Ellipsis, 'sum': <built-in function sum>, 'set': <class 'set'>, 'FileExistsError': <class 'FileExistsError'>, 'setattr': <built-in function setattr>, '__package__': '', 'isinstance': <built-in function isinstance>, 'RuntimeWarning': <class 'RuntimeWarning'>, 'ProcessLookupError': <class 'ProcessLookupError'>, 'NotImplemented': NotImplemented, 'zip': <class 'zip'>, 'issubclass': <built-in function issubclass>, 'IOError': <class 'OSError'>, 'eval': <built-in function eval>, 'filter': <class 'filter'>, 'FileNotFoundError': <class 'FileNotFoundError'>, 'credits':     Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands
    for supporting Python development.  See www.python.org for more information., 'sorted': <built-in function sorted>, 'open': <built-in function open>, 'hasattr': <built-in function hasattr>, 'UnicodeEncodeError': <class 'UnicodeEncodeError'>, 'bool': <class 'bool'>, 'dict': <class 'dict'>, 'AttributeError': <class 'AttributeError'>, 'float': <class 'float'>, 'TabError': <class 'TabError'>, 'ImportWarning': <class 'ImportWarning'>, 'bytes': <class 'bytes'>, 'pow': <built-in function pow>, 'enumerate': <class 'enumerate'>, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, 'globals': <built-in function globals>, 'ChildProcessError': <class 'ChildProcessError'>, 'StopIteration': <class 'StopIteration'>, 'FutureWarning': <class 'FutureWarning'>, '__import__': <built-in function __import__>, 'MemoryError': <class 'MemoryError'>, 'PendingDeprecationWarning': <class 'PendingDeprecationWarning'>, 'ConnectionRefusedError': <class 'ConnectionRefusedError'>, 'SystemError': <class 'SystemError'>, 'TypeError': <class 'TypeError'>, 'next': <built-in function next>, 'quit': Use quit() or Ctrl-D (i.e. EOF) to exit, 'ArithmeticError': <class 'ArithmeticError'>, 'LookupError': <class 'LookupError'>, 'ascii': <built-in function ascii>, 'id': <built-in function id>, 'slice': <class 'slice'>, 'bytearray': <class 'bytearray'>, 'ImportError': <class 'ImportError'>, 'oct': <built-in function oct>, 'BufferError': <class 'BufferError'>, 'callable': <built-in function callable>, '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.", 'reversed': <class 'reversed'>, 'object': <class 'object'>, 'len': <built-in function len>, 'frozenset': <class 'frozenset'>, 'round': <built-in function round>, 'Exception': <class 'Exception'>, 'hash': <built-in function hash>, 'AssertionError': <class 'AssertionError'>, 'ConnectionAbortedError': <class 'ConnectionAbortedError'>, 'RecursionError': <class 'RecursionError'>, 'range': <class 'range'>, 'ValueError': <class 'ValueError'>, 'abs': <built-in function abs>, 'compile': <built-in function compile>, 'False': False, 'chr': <built-in function chr>, 'bin': <built-in function bin>, 'UnboundLocalError': <class 'UnboundLocalError'>, 'str': <class 'str'>, 'UnicodeTranslateError': <class 'UnicodeTranslateError'>, 'map': <class 'map'>, 'DeprecationWarning': <class 'DeprecationWarning'>, 'property': <class 'property'>, 'TimeoutError': <class 'TimeoutError'>, 'vars': <built-in function vars>, 'BytesWarning': <class 'BytesWarning'>, 'ConnectionResetError': <class 'ConnectionResetError'>, 'SyntaxWarning': <class 'SyntaxWarning'>, 'True': True, 'ConnectionError': <class 'ConnectionError'>, 'KeyboardInterrupt': <class 'KeyboardInterrupt'>, 'help': Type help() for interactive help, or help(object) for help about object., 'ReferenceError': <class 'ReferenceError'>, '__build_class__': <built-in function __build_class__>, 'all': <built-in function all>, 'tuple': <class 'tuple'>, 'Warning': <class 'Warning'>, 'int': <class 'int'>, 'memoryview': <class 'memoryview'>, 'BlockingIOError': <class 'BlockingIOError'>, 'copyright': Copyright (c) 2001-2016 Python Software Foundation.
All Rights Reserved.

Copyright (c) 2000 BeOpen.com.
All Rights Reserved.

Copyright (c) 1995-2001 Corporation for National Research Initiatives.
All Rights Reserved.

Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
All Rights Reserved., 'UnicodeWarning': <class 'UnicodeWarning'>, 'exit': Use exit() or Ctrl-D (i.e. EOF) to exit, 'divmod': <built-in function divmod>, 'IndentationError': <class 'IndentationError'>, 'complex': <class 'complex'>, 'ZeroDivisionError': <class 'ZeroDivisionError'>, 'IsADirectoryError': <class 'IsADirectoryError'>, 'FloatingPointError': <class 'FloatingPointError'>, 'repr': <built-in function repr>, 'license': Type license() to see the full license text, '__name__': 'builtins', 'input': <built-in function input>, 'KeyError': <class 'KeyError'>}, '__doc__': None, '__file__': '/home/jeco/anaconda3/lib/python3.5/site-packages/gi/__init__.py', '__cached__': '/home/jeco/anaconda3/lib/python3.5/site-packages/gi/__pycache__/__init__.cpython-35.pyc', 'requests': <module 'requests' from '/home/jeco/anaconda3/lib/python3.5/site-packages/requests/__init__.py'>, '__package__': 'gi', 'save_file': <function save_file at 0x7f9392f538c8>, '__spec__': ModuleSpec(name='gi', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f9392f6c3c8>, origin='/home/jeco/anaconda3/lib/python3.5/site-packages/gi/__init__.py', submodule_search_locations=['/home/jeco/anaconda3/lib/python3.5/site-packages/gi']), '__path__': ['/home/jeco/anaconda3/lib/python3.5/site-packages/gi'], 'sys': <module 'sys' (built-in)>, 'json': <module 'json' from '/home/jeco/anaconda3/lib/python3.5/json/__init__.py'>, '__name__': 'gi', 'GIST_API_URL': 'https://api.github.com/gists', 'GistError': <class 'gi.GistError'>}

**Comment by maateen** [comment]
Thanks for your valuable information. Actually you are using `/home/jeco/anaconda3/bin/python3` as your python executable instead of `/usr/bin/python3`. That's why the problem is occurring.

Perhaps, I will fix the problem by using `/usr/bin/python3` instead of `python3`.

**Comment by maateen** [comment]
I have made a new commit in `devel` branch to fix this issue. Please try these and let me know the update:

```
wget https://github.com/maateen/battery-monitor/archive/devel.zip
```
```
unzip devel.zip
```
```
cd battery-monitor-devel
```
```
sudo make install
```
Also make sure you have installed all dependencies.

**Comment by jecogeo** [comment]
@maateen, thanks a lot. I installed battery-monitor as indicated. The command `battery-monitor` now executed like expected in the terminal. I also added the command to startup applications and it's now listed in processes list after reboot. So it's probably working like a charm (I've not seen notifications yet likely because of my battery status, but as it is listed in processes list I assume it is running ok). Thanks again.

**Comment by maateen** [comment]
Battery Monitor should run automatically at startup. You need not do so manually. If you have doubt about notification, please test it with following command:

```
/usr/share/battery-monitor/battery-monitor.py --test
```

Now sit tight and wait. You will see various notification for various situation. Let me know if any issue occurs. Otherwise, please close the bug if you can.

**Comment by jecogeo** [comment]
It's working very well now. Thanks for your help!
Best regards.
