### ISSUE TITLE
Insert battery icon in tray

### ISSUE THREAD

**Issue by Fabioamd87** [maateen/battery-monitor#46]
Hi I would like to replace the battery icon status in LXDE with something else. I've came into this software and I founded it really useful because of the lack of notificationon of LXDE icon.

Another think that I would like is to have the percentage next to the status and better icon (themable).
Also some tooltip would be nice if you go with the cursor on it.

**Comment by maateen** [comment]
@Fabioamd87 Thanks for your excellent idea. We will try to implement the idea in upcoming v0.6 version.

**Comment by Fabioamd87** [comment]
thanks! if you need any help in testing I'm here with my stock LXDE on *buntu 17.04.

**Comment by maateen** [comment]
Sure. But I am afraid that we will take 3-4 months to release v0.6. Your patience is appreciated.
