### ISSUE TITLE
Notification displays for very short time.

### ISSUE THREAD

**Issue by sunilsong** [maateen/battery-monitor#47]
Battery monitor is working fine. But, it shows notification for very less time, not even one second.

**Comment by maateen** [comment]
Seriously? This bug was fixed once as far as I can remember. Please let me know your system information.

**Comment by sunilsong** [comment]
ya. I am running ubuntu gnome 16.10 64-bit. let me know, if you need any information.

**Comment by maateen** [comment]
@sunilsong Sorry to reply lately. Please use [Beta](https://github.com/maateen/battery-monitor#for-beta-testers) and confirm the bug. Once, you have confirmed, we'll try to fix.

**Comment by sunilsong** [comment]
@maateen I have installed the beta. Now, It is working fine. Thank you.

**Comment by maateen** [comment]
Thanks for the information. As soon as possible, I'll merge the Beta with Stable one and push to the PPA.
