### ISSUE TITLE
No Auto start

### ISSUE THREAD

**Issue by meetdilip** [maateen/battery-monitor#5]
I added **battery-monitor** as command in start up. But the app does not auto start when the system is started. What is the exact command to be used in start up ? Or something else is preventing auto start ?

![battery](https://cloud.githubusercontent.com/assets/6965443/17130261/48e78958-5335-11e6-9635-9087a7540ad9.png)

**Comment by maateen** [comment]
Please remove it. Then give me the output of the command:
```
cat /etc/init/battery-monitor.conf
```
Also make sure, you are using the latest version.

**Comment by meetdilip** [comment]
Here you go

```
$ cat /etc/init/battery-monitor.conf
# myservice - myservice job file

description "It's a Python3 script which will notify user about charging, discharging and not charging state of the battery on Linux. It's using PyGtk3 for notification."
author "Maksudur Rahman Maateen <maateen@outlook.com>"

# Stanzas
#
# Stanzas control when and how a process is started and stopped
# See a list of stanzas here: http://upstart.ubuntu.com/wiki/Stanzas#respawn

# When to start the service
start on runlevel [2345]

# When to stop the service
stop on runlevel [016]

# Automatically restart process if crashed
respawn

# Essentially lets upstart know the process will detach itself to the background
expect fork

# Run before process
pre-start script
    exec battery-monitor
end script

# Start the process
exec myprocess
```

**Comment by maateen** [comment]
Everything is fine. Now remove battery monitor from Startup Applications program. Then reboot. I hope battery monitor will start automatically.

> Or something else is preventing auto start ?
May be. You can check into system.

**Comment by meetdilip** [comment]
How to check if battery monitor is running ?

PS : I just restarted the system

**Comment by maateen** [comment]
Plug and unplug the power source. You should get notification. Also give me the output from terminal:
```
ps aux | grep battery-monitor
```

**Comment by meetdilip** [comment]
No notification when I switch off and ON the power plug
`
My-PC      15878  0.0  0.0  14224  1032 pts/0    S+   18:20   0:00 grep --color=auto battery-monitor`

**Comment by meetdilip** [comment]
I still get no auto start for the app.

**Comment by maateen** [comment]
`battery-monitor` is the command that plays to run the real script. Try `battery-monitor` command on terminal, then try `ps aux | grep battery-monitor` on another terminal without exiting the previous command process. Show me the output please.

**Comment by meetdilip** [comment]
Here is the output of ps aux | grep battery-monitor

My-PC      20902  0.0  0.0  12544  2060 pts/2    S+   13:51   0:00 /bin/bash /usr/bin/battery-monitor
My-PC      20913 38.4  0.5 421912 22184 pts/2    Sl+  13:51  81:18 python3 /usr/share/battery-monitor/battery-monitor.py
My-PC      26188  0.0  0.0  14224   928 pts/8    S+   17:23   0:00 grep --color=auto battery-monitor

**Comment by maateen** [comment]
I see. What about other things I stated before?

**Comment by meetdilip** [comment]
@maateen Like ? I tried all commands you gave ? You want me to try python3 /usr/share/battery-monitor/battery-monitor.py  ?

**Comment by maateen** [comment]
Welcome. I hope, I will introduce more features in next release.

**Comment by maateen** [comment]
@meetdilip We have released a new version of **Battery Monitor**. Please try that and let us whether the problem has been fixed or not. Here is the details: http://battery-monitor.maateen.me/
