### ISSUE TITLE
Seeing battery notifications ever 1% on ubuntu 16.04

### ISSUE THREAD

**Issue by arooni** [maateen/battery-monitor#51]
I love the idea but I'm seeing every time the battery decreases 1 percent I'm seeing a notification ; I was hoping to see one only when I hit a new threshold.  Ideas?

**Comment by maateen** [comment]
Hi @arooni, thanks for your suggestion. Can you please elaborate the idea more?

**Comment by arooni** [comment]
Thanks for the quick response.  I assumed your software worked like this, or would ideally work lie this (I will use the example you have on your readme for battery % amounts for simplicity):

Take out the laptop from charger -- get a notification that i did that with % battery remaining. Battery is at 100%.

Battery at 100-91% -- no notification needed because we havent dropped at or below any threshold.

Battery at 90% -- hit 3rd custom warning, show me ONE notification, ONE TIME that i hit 90%

Battery at 89% - 76%  -- no notification needed since i haven't hit the second custom warning yet

Battery at 75% -- hit 2nd custom warning -- show me the warning ONE TIME with ONE NOTIFICATION.

i.e. so forth and so on.... the idea is I don't need updates every % my battery drops, just the FIRST time I hit a new threshold.

unrelated question: what is notification stability?  It doesn't seem to be explained on the main gitthub readme page.  thanks again!

**Comment by arooni** [comment]
Essentially with your software as is, I'm getting a notification EVERY MINUTE.. which seems like too much right?  I'd like notirfications only at certain events

**Comment by maateen** [comment]
@arooni, I am very sorry for my reply at late. Actually, I was very busy with some other kinds of stuff. You point seems to be a strong valid point to me. Please let me mark this as 'logical' bug and fix in next version.

**Comment by JacobGates** [comment]
Hey maateen, I just installed batter-monitor on ubuntu 16.04 and I'm having this happen as well. Was wondering if you updated it to fix this bug yet and I'm having a slightly different problem or if the bug is still there? Mine is exactly as described above, every single percent I get an notification. I'm also using gnome 3.18 if that helps.

**Comment by FabrizioMarana** [comment]
No action required.  Just wanted to leave a message I'm affected as well. I agree with Arooni, except for one thing: Whenever the cable is plugged in or removed, Battery Monitor can show a message as well (charging or discharging)  :-)

**Comment by maateen** [comment]
@FabrizioMarana Thanks for your valuable comment. We'll try our level best to act accordingly.
