### ISSUE TITLE
Feature-request: Low + Critical battery

### ISSUE THREAD

**Issue by FabrizioMarana** [maateen/battery-monitor#53]
First of all: *thanks for making this.*  This was exactly what I was looking for!

This feature request is an easy one: rename the existing red low-battery.png to critical-battery, color the existing red low-battery.png in orange and call that one low-battery.

(industry standard for "Very Low Battery" = "Critical Battery")

**Comment by maateen** [comment]
Thanks for your awesome suggestion. We'll try our level best to implement this in next release.

**Comment by maateen** [comment]
Update: We have already added some new icons, fully ready for new release. Please stay connected to feel the chill.
