### ISSUE TITLE
18.04 support

### ISSUE THREAD

**Issue by MatzFan** [maateen/battery-monitor#55]
Bionic Beaver final is out today, will `battery-monitor` support this distro?

**Comment by maateen** [comment]
It's already supported.

**Comment by maateen** [comment]
@MatzFan, please ignore my previous comment. We have the plan to support Ubuntu 18.04 in our next release.

**Comment by maateen** [comment]
@MatzFan Until we release a deb file for Ubuntu 18.04, you can install **Battery Monitor** using [this](https://github.com/maateen/battery-monitor#common-method).

**Comment by MatzFan** [comment]
@maateen - poor choice of wording on my part, I meant to ask about 18.04 in PPA. Happy to install direct from GitHub in the meantime. Many thanks.

**Comment by maateen** [comment]
No worries.

**Comment by maateen** [comment]
We have released [v0.6 Beta](https://github.com/maateen/battery-monitor/tree/devel#v06) in our PPA channel. Please check and chill.

**Comment by RoldanLT** [comment]
battery-monitor is already the newest version (0.5.3-artful)

**Comment by RoldanLT** [comment]
This works but can't save settings: https://launchpad.net/~maateen/+archive/ubuntu/battery-monitor/+files/battery-monitor_0.6-beta-2-artful_all.deb

**Comment by maateen** [comment]
We have got this bug report already. We'll make a quick fix today/tomorrow.
