### ISSUE TITLE
Icons do not appear, GUI does not open

### ISSUE THREAD

**Issue by yochananmarqos** [maateen/battery-monitor#58]
Battery Monitor runs, but does not show the icons in the toast notification. The menu entries also do not have icons. Battery Monitor GUI does not run at all. It still does not run at startup as in #48 

```
$ /usr/bin/python3 /usr/share/battery-monitor/battery-monitor-gui.py
Traceback (most recent call last):
  File "/usr/share/battery-monitor/battery-monitor-gui.py", line 141, in <module>
    win = MainWindow()
  File "/usr/share/battery-monitor/battery-monitor-gui.py", line 22, in __init__
    self.set_default_icon_from_file(os.path.join(path, 'icons/icon.png'))
GLib.Error: g-file-error-quark: Failed to open file “/usr/share/battery-monitor/icons/icon.png”: Permission denied (2)
```
It appears it installed properly:

```
$ sudo find / -type f -print | grep 'battery-monitor'
/usr/bin/battery-monitor
/usr/share/battery-monitor/config.py
/usr/share/battery-monitor/icons/discharging.png
/usr/share/battery-monitor/icons/charging.png
/usr/share/battery-monitor/icons/not-charging.png
/usr/share/battery-monitor/icons/low-battery.png
/usr/share/battery-monitor/icons/icon.png
/usr/share/battery-monitor/battery-monitor-gui.py
/usr/share/battery-monitor/battery-monitor.py
/usr/share/applications/battery-monitor.desktop
/usr/share/applications/battery-monitor-gui.desktop
find: ‘/run/user/1000/gvfs’: Permission denied
/etc/xdg/autostart/battery-monitor-autostart.desktop
```

`python` 3.6.5
`python-gobject` 3.28.2
`libnotify` 0.7.7
`acpi` 1.7

Manjaro Linux Cinnamon

**Comment by maateen** [comment]
Thanks for your report. Can you please try our [v0.6 beta](https://github.com/maateen/battery-monitor/tree/devel#for-developers) and share your feedback with us?

**Comment by yochananmarqos** [comment]
No difference.

**Comment by maateen** [comment]
Thanks for your feedback. Please, make sure that you have installed all [dependencies](https://github.com/maateen/battery-monitor/tree/devel#dependencies). Now, please play the following command after installing our [v0.6 beta](https://github.com/maateen/battery-monitor/tree/devel#for-developers):

```bash
username=`whoami`
chown $username:$username -R /usr/share/battery-monitor
```
Now please run battery monitor in test mode and share your feedback:

```
python3 /usr/share/battery-monitor/run.py --test
```

**Comment by yochananmarqos** [comment]
Again, I have the following dependencies installed:

`python` 3.6.5
`python-gobject` 3.28.2
`libnotify` 0.7.7
`acpi` 1.7

`gir1.2-appindicator3-0.1` is not in the Manjaro or Arch repo's and I can't find what the equivalent package would be. 

```
$ python3 /usr/share/battery-monitor/run.py --test
python3: can't open file '/usr/share/battery-monitor/run.py': [Errno 2] No such file or directory
$ cd /usr/share/battery-monitor
$ ls
battery-monitor-gui.py  battery-monitor.py  config.py  icons
```

**Comment by maateen** [comment]
Have you really followed the instructions correctly? In that case you should have as follows:

```bash
$ ls /usr/share/battery-monitor               
AppIndicator.py  BatteryMonitor.py  config.py  icons  __init__.py  Notification.py  run.py  SettingsWindow.py
```
Please check here again: https://github.com/maateen/battery-monitor/tree/devel#for-beta-testers

**Comment by yochananmarqos** [comment]
Aha! The beta version did the trick. Icons are appearing, tray icon is present and the GUI opens. I already had all the dependencies. By the way, there is no `libappindicator3-1`, but there is `libappindicator-gtk3` (installed), `libappindicator-gtk2`, `python2-libappindicator` & `libappindicator-sharp` as well as the `lib32` versions. 

I was thinking I might add Battery Monitor to the [AUR](https://aur.archlinux.org/), but at this point I could only submit the devel branch as master does not work right. 

```
$ python3 /usr/share/battery-monitor/run.py --test
Battery 0: Discharging, 63%, 00:10:12 remaining
Config file is missing or not readable. Using default configurations.

(run.py:15999): Gdk-CRITICAL **: 14:36:51.415: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Battery 0: Full, 83%, discharging at zero rate - will never fully discharge
Battery 0: Discharging, 2%, discharging at zero rate - will never fully discharge
Battery 0: Full, 64%, 01:47:31 remaining
Battery 0: Full, 68%, discharging at zero rate - will never fully discharge
Battery 0: Discharging, 45%, 01:47:31 remaining
Battery 0: Discharging, 6%, discharging at zero rate - will never fully discharge
Battery 0: Charging, 39%, 03:24:25 remaining
```

**Comment by maateen** [comment]
It'll be great if you can add **Battery Monitor** to [AUR](https://aur.archlinux.org/). If you are ready to support the repo continuously, we can declare it as official AUR package.
You have already opened a new issue (#59) regarding AUR package. We can discuss the matter there.
