### ISSUE TITLE
Makefile issue during PKGBUILD

### ISSUE THREAD

**Issue by yochananmarqos** [maateen/battery-monitor#59]
I tried [creating](https://wiki.archlinux.org/index.php/Creating_packages) a [PKGBUILD](https://wiki.archlinux.org/index.php/PKGBUILD), but I get an error during install:

PKGBUILD:
```
pkgname=battery-monitor-devel
pkgver=0.6.1
pkgrel=1
pkgdesc='A utility tool, notifies user about charging, discharging and not charging state of the battery on Linux.'
arch=('x86_64')
url="https://github.com/maateen/battery-monitor"
license=('GPL3')
depends=('python-gobject' 'python2-gobject' 'gtk3' 'libappindicator-gtk3' 'acpi' 'libnotify')
makedepends=('git')
conflicts=('battery-monitor')
provides=('battery-monitor')
source=("$pkgname"::'git+https://github.com/maateen/battery-monitor.git#branch=devel')
md5sums=('SKIP')

package() {
	cd "$srcdir/${pkgname}"
	make OUT_DIR="$pkgdir" install
}
```

Result:
```
$ makepkg -si
==> Making package: battery-monitor-devel 0.6.1-1 (Thu May 24 09:24:59 MDT 2018)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating battery-monitor-devel git repo...
Fetching origin
==> Validating source files with md5sums...
    battery-monitor-devel ... Skipped
==> Extracting sources...
  -> Creating working copy of battery-monitor git repo...
Reset branch 'makepkg'
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
You must be root to install.
cp: cannot create regular file '/usr/bin/battery-monitor': Permission denied
make: *** [Makefile:18: install] Error 1
==> ERROR: A failure occurred in package().
    Aborting...
```
I created [a post on the Manjaro Forums](https://forum.manjaro.org/t/issues-creating-first-pkgbuild/47976) and I was [told](https://forum.manjaro.org/t/issues-creating-first-pkgbuild/47976/4), 

> Upstream Makefile has no PREFIX or similar variable, it has an explicit install path. This is a Bad Thing as it’s not even installing into /usr/local/.

**Comment by maateen** [comment]
I have made a fix in commit ea7e2d0 for this issue. Please check and let me know the update.

**Comment by yochananmarqos** [comment]
A slightly different error this time:

```
==> Entering fakeroot environment...
==> Starting package()...
You must be root to install.
install -d /usr/share/battery-monitor
install: cannot change permissions of ‘/usr/share/battery-monitor’: No such file or directory
make: *** [Makefile:9: install] Error 1
==> ERROR: A failure occurred in package().
    Aborting...
```
This is my first time creating a PKGBUILD, so I'm not sure if I need to change anything. I also get the same result after simplifying it a little:

```
package() {
	cd "$srcdir/${pkgname}"
	make install
}
```

**Comment by maateen** [comment]
Okay, I got the point. I think you need to write a very own Makefile for PKGBUILD. You can surf around and can do this. I have no Arch machine and I am unable to do trial and error.

**Comment by yochananmarqos** [comment]
Well, you could install Manjaro in a virtual machine if you wanted. I'll see what I can come up with.

**Comment by yochananmarqos** [comment]
Got it! I skipped your Makefile and did this:

```
package() {
	cd "$srcdir/${pkgname}"
	install -d "${pkgdir}/usr/share/battery-monitor"
	cp -a src/. "${pkgdir}/usr/share/battery-monitor"
	mkdir -p "${pkgdir}/usr/local/bin/battery-monitor"
	install -Dm755 battery-monitor "${pkgdir}/usr/local/bin/battery-monitor"
	install -Dm755 battery-monitor-autostart.desktop "${pkgdir}/etc/xdg/autostart/battery-monitor-autostart.desktop"
	install -Dm755 battery-monitor.desktop "${pkgdir}/usr/share/applications/battery-monitor.desktop"
}
```

**Comment by yochananmarqos** [comment]
I uploaded it to the AUR: https://aur.archlinux.org/packages/battery-monitor-devel/

**Comment by maateen** [comment]
Is it working fine? Thanks a lot in that case. Please give me necessary documentation here so that I can add in README. Otherwise, please open a PR in devel branch.

**Comment by yochananmarqos** [comment]
Yes, it's working great. All you have to put in your README is something like, 

> For Arch users, the beta version is available in the [AUR](https://aur.archlinux.org/packages/battery-monitor-devel/).

I'll make a separate PKGBUILD for the stable version once the beta version graduates.

**Comment by maateen** [comment]
Can you please make a PR to devel branch? Thus, you can be enlisted as our contributor. :heart:

**Comment by yochananmarqos** [comment]
I created a PR to update the README, but I'm still not sure why the Makefile didn't work in the PKGBUILD. If I figure it out, I'll let you know.

**Comment by maateen** [comment]
That'll be helpful for us. Thanks a lot for your contribution. We have added you to our contributor space.
