### ISSUE TITLE
No entry in dash

### ISSUE THREAD

**Issue by meetdilip** [maateen/battery-monitor#6]
When I type " battery " in dash ( Unity in 16.04 ), I am not able to find any entries name **Battery Monitor**. Is it the standard behaviour ?

**Comment by maateen** [comment]
The **Battery Monitor** is in beta. Till now, there is no dash icon. But I will add one very soon.

**Comment by meetdilip** [comment]
No problem. Thanks.

**Comment by maateen** [comment]
@meetdilip We have released a new version of **Battery Monitor**. Please try that and let us whether the problem has been fixed or not. Here is the details: http://battery-monitor.maateen.me/
