### ISSUE TITLE
Preferences do not save if custom warning field is blank

### ISSUE THREAD

**Issue by yochananmarqos** [maateen/battery-monitor#61]
After [this commit](https://github.com/maateen/battery-monitor/commit/83e7ca8570bf101eb8e5612924189adfce0a3c8e), the preferences will not save if one of the custom warning fields are left blank. Also, when it does save with values in all fields, the preferences window does not close.

**Comment by maateen** [comment]
Thanks a lot for the bug report. We'll make a quick fix soon.

**Comment by maateen** [comment]
@yochananmarqos I have made a new commit. It should fix the bug. Can you please check?

**Comment by yochananmarqos** [comment]
Yes, that fixed the issue with not being able to save with blank values. Is the preferences window supposed to close after saving? I thought it did before.

**Comment by maateen** [comment]
For which fields are you not able to save? **Low Battery**, **Critical Battery** and **Notification Stability** are mandatory fields. You can leave custom warning fields blank.

**Comment by yochananmarqos** [comment]
I just said it was fixed. I was only asking why the preferences dialog does not close after saving. After pressing save, I get the confirmation dialog that changes were successfully saved, I press OK, but the preferences window is still open.

**Comment by maateen** [comment]
@yochananmarqos New commit pushed. Hope it has fixed the issue finally.

**Comment by yochananmarqos** [comment]
Yep, that did the trick.
