### ISSUE TITLE
Program wont start

### ISSUE THREAD

**Issue by nahmias22** [maateen/battery-monitor#67]
Hi, I installed your application on Ubuntu 18.04 and have checked that all the dependencies were installed (before running the installation) but when trying to run your application nothing happens. Is there some terminal command I could try using?

**Comment by maateen** [comment]
We are very sorry to hear that the programs didn't start. Please try the following command on Terminal and let us know the output:

```
battery-monitor
```

**Comment by nahmias22** [comment]
So I just tried that and below is the response I got:
~$ battery-monitor
Traceback (most recent call last):
  File "/usr/share/battery-monitor/run.py", line 14, in <module>
    from AppIndicator import AppIndicator
  File "/usr/share/battery-monitor/AppIndicator.py", line 10, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

The thing is the library is already installed. Do I need to enable it in some way?

**Comment by maateen** [comment]
Please, cross-check that you have installed `libappindicator3-1`. If it has been installed already, then please run the following command:

```bash
sudo apt install gir1.2-appindicator3-0.1
```

**Comment by nahmias22** [comment]
Now it worked thanks!

**Comment by maateen** [comment]
That's great. We have updated our README based on your feedback. Thanks.
