### ISSUE TITLE
Propose Logo/icon

### ISSUE THREAD

**Issue by mirzazulfan** [maateen/battery-monitor#68]
Hi @maateen ..I'm a graphic designer and an open source enthusiast. I would like to contribute to your awesome project by proposing logo design for it if you allow me. I'll be doing it as a gift for free to your awesome project.
Best regard. 
Mirza zulfan.

**Comment by maateen** [comment]
@mirzazulfan Thanks for your proposal. This is an opensource project. Please feel free to design a logo and some icons for us. ❤️

**Comment by mirzazulfan** [comment]
Thanks for your response. I'll do my best. If you have an idea please share with me, it would be better for me. :)

**Comment by mirzazulfan** [comment]
Hi @maateen .. i've designed some logos for you project. If there is something you want to change please let me know.
![battery](https://user-images.githubusercontent.com/36124339/42337760-ec1f8f66-80b1-11e8-82e3-fe5c15c9ba7f.png)

**Comment by maateen** [comment]
Thanks for your effort. These logos are awesome. But we need something different, polished and for creative. Please take a look at our previous icon sets.

**Comment by mirzazulfan** [comment]
I'll try to make it better. Thanks for your feedback sir.
