### ISSUE TITLE
Battery monitor doesn't start

### ISSUE THREAD

**Issue by nishant-mor** [maateen/battery-monitor#69]
Battery monitor doesn't start,
It just blinks few time in side panel and then goes away.

Ubuntu 16.04 LTS

**Comment by nishant-mor** [comment]
Output of battery-monitor in terminal : 

Traceback (most recent call last):
  File "/usr/share/battery-monitor/run.py", line 14, in <module>
    from AppIndicator import AppIndicator
  File "/usr/share/battery-monitor/AppIndicator.py", line 29
    TEST_MODE: bool
             ^
SyntaxError: invalid syntax

**Comment by maateen** [comment]
We have the same issue #63 opened. This occurs due to the Python version mismatch. Our current code has been written in Python3.6. But Ubuntu 16.04 has Python3.5 installed built-in.

We are looking into the issue and post the updates in #63
