### ISSUE TITLE
Uses too much CPU

### ISSUE THREAD

**Issue by saks** [maateen/battery-monitor#7]
Every time I run it, I see this:
![1](https://cloud.githubusercontent.com/assets/99110/17134695/534fd02a-535e-11e6-85e3-a83fa2a35994.png)
![2](https://cloud.githubusercontent.com/assets/99110/17134698/58ab586e-535e-11e6-8c14-218b7aab2a19.png)
```
$ cat /etc/issue
Ubuntu 16.04.1 LTS
$ uname -a
Linux CB-003 4.4.0-33-generic #52-Ubuntu SMP Fri Jul 22 19:16:44 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
Any ideas?

**Comment by maateen** [comment]
Yah, it's a CPU drainer app.

**Comment by maateen** [comment]
I will work on this matter and decrease the CPU usage. So, I am making this issue open.

**Comment by maateen** [comment]
Update: Marked as bug.
