### ISSUE TITLE
Error in AppIndicator.py

### ISSUE THREAD

**Issue by JTFlavier** [maateen/battery-monitor#70]
Hello!

I am currently using Debian 9.5 Cinnamon.

I tried installing Battery Monitor using the common method (`wget, unzip, cd, sudo make install`). However, when I try to run Battery Monitor using the desktop environment, nothing happens. Running Battery Monitor using the command line yields the following error:

```
Traceback (most recent call last):
  File "/usr/share/battery-monitor/run.py", line 14, in <module>
    from AppIndicator import AppIndicator
  File "/usr/share/battery-monitor/AppIndicator.py", line 29
    TEST_MODE: bool
             ^
SyntaxError: invalid syntax
```

**Comment by maateen** [comment]
We have the same issue #63 opened. This occurs due to the Python version mismatch. Our current code has been written in Python3.6. But Ubuntu 16.04 has Python3.5 installed built-in.

We are looking into the issue and post the updates in #63
