### ISSUE TITLE
Namespace AppIndicator3 not available

### ISSUE THREAD

**Issue by jeanbruder** [maateen/battery-monitor#74]
Just installed "battery monitor" using PPA on Ubuntu 18.04.01 LTS, and after starting from the command line :

> jean@AstuX:~$ battery-monitor 
> Traceback (most recent call last):
>  File "/usr/share/battery-monitor/run.py", line 14, in <module>
>    from AppIndicator import AppIndicator
>  File "/usr/share/battery-monitor/AppIndicator.py", line 10, in <module>
>    gi.require_version('AppIndicator3', '0.1')
>  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
>    raise ValueError('Namespace %s not available' % namespace)
> ValueError: Namespace AppIndicator3 not available

Can you please help ?

**Comment by spiritmoii** [comment]
Did you verify you have all the dependencies:
    acpi
    python3
    python3-gi
    python3-setuptools
    libnotify4
    libappindicator3-1
    gir1.2-appindicator3-0.1

**Comment by jeanbruder** [comment]
So sorry guys, I have read the prerequisites after installing the package ... Afterwards, once all has been installed, everything is working fine ! Thank's so much !
