### ISSUE TITLE
Using 'upower' instead of 'acpi -b'

### ISSUE THREAD

**Issue by maateen** [maateen/battery-monitor#8]
```
upower -i /org/freedesktop/UPower/devices/battery_BAT0
```
This command comes default with Ubuntu. Let's use it, instead of `acpi -b`.

**Comment by meetdilip** [comment]
How does it help ? UPower failed to give me notifications at 30 % for low battery. I had to use a custom script.

**Comment by maateen** [comment]
Really? Can you produce the error and paste here? Please!

**Comment by maateen** [comment]
Really? Can you produce the error and paste here? Please!

**Comment by meetdilip** [comment]
I have been hunting for low battery app since some time. I have 16.04 and was try to make me notify at 30 %. Which was not happening even after I tried 

`sudo apt-get install --reinstall indicator-power`

I was using a custom script till I found Battery Monitor app on OMG Ubuntu.

**Comment by maateen** [comment]
Feeling happy to make something useful. Are you getting warning at 10% from battery-monitor app?

**Comment by meetdilip** [comment]
Yes, I got a warning. And, I guess it is from your app :)

**Comment by maateen** [comment]
Using 'upower' instead of 'acpi -b' is nothing but a bad idea. I will keep using `acpi -b`.
