### ISSUE TITLE
Programm not opening 

### ISSUE THREAD

**Issue by Schipi1993** [maateen/battery-monitor#82]
Hi there! I’m I’m new to Linux ! Just installed Ubuntu 18.4 LTS to my Asus K50ij
I’m totally happy with the system except for battery management!
My battery was broken so I replaced it.  Now I want to have him running on battery in order to keep the battery healthy. But Linux doesn’t notify me in a very good way when it runs out of battery so I d like to use battery monitor but it does not open, why?
Many thanks in advance!

**Comment by yochananmarqos** [comment]
Please run `battery-monitor` from the terminal and post the output here.

**Comment by Schipi1993** [comment]
:~$ battery-monitor
Traceback (most recent call last):
  File "/usr/share/battery-monitor/run.py", line 14, in <module>
    from AppIndicator import AppIndicator
  File "/usr/share/battery-monitor/AppIndicator.py", line 10, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

**Comment by yochananmarqos** [comment]
How did you [install ](https://github.com/maateen/battery-monitor#installation)it? Did you add the PPA or build from source? You're missing [dependencies](https://github.com/maateen/battery-monitor#dependencies).

**Comment by Schipi1993** [comment]
Yes I did by PPA! Guess I found the solution, manually install Appindicator 3 by Sudo?
If you think that won’t help please replay again! I’ll try it tomorrow cause now the machine is in use with something else I don’t want to interrupt on a non admin account!
Thank you

**Comment by yochananmarqos** [comment]
No, you need `libappindicator3-1` & `gir1.2-appindicator3-0.1` from the Ubuntu repos.  They should have been installed as [dependencies](https://github.com/maateen/battery-monitor#dependencies), are they installed?

**Comment by Schipi1993** [comment]
Believe it or not the last post on this page fixed it for me!😂

**Comment by yochananmarqos** [comment]
...that's what I just said. Glad you figured it out.
