### ISSUE TITLE
10 hours remaining at 10% battery left?

### ISSUE THREAD

**Issue by maateen** [maateen/battery-monitor#9]
From reddit
> I'm more interested in that battery then in the software, 10 hours remaining at 10% battery left? Amazing :-D amazing GIMP/Photoshop skills that is. But have to admit, it looks better then the original Ubuntu one.

**Comment by maateen** [comment]
Anyone got the same issue, please?

**Comment by meetdilip** [comment]
At 100%, I got 4500:00:00. Something is wrong with balance battery esitmate.

**Comment by maateen** [comment]
Please show me the output of `acpi -b` when you got the same error.

**Comment by meetdilip** [comment]
Discharging 99 % 2:11:13

Works fine now

> Battery 0: Discharging, 99%, 02:41:36 remaining
